Added blog about flash removal
videojs/blog pull request #14
Opened 2017-01-25 20:25 UTC by mrocajr

2017-01-25 20:29 UTC, jakemingolla commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +to allow developer to continue to support legacy browsers by adding the tech themselves, while allowing
developer -> developers

2017-01-25 20:31 UTC, mrocajr commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +to allow developer to continue to support legacy browsers by adding the tech themselves, while allowing
Thanks:)

2017-01-26 19:38 UTC, brandonocasey reviewed
Two comment LGTM otherwise

2017-01-26 19:38 UTC, BrandonOCasey commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +This follows in the footsteps of Chrome, Safari and Firefox which are all taking steps to depricate flash.
...steps to ~~depricate~~ deprecate flash...

2017-01-26 19:40 UTC, BrandonOCasey commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +  - videojs 6
should be `video.js 6.0` for consistency

2017-01-26 20:00 UTC, mrocajr commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +This follows in the footsteps of Chrome, Safari and Firefox which are all taking steps to depricate flash.
Thanks!  Fixed it.

2017-01-26 20:01 UTC, BrandonOCasey commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +  - videojs 6.0
needs to `video.js 6.0` with the `.` between `video` and `js`

2017-01-26 20:03 UTC, mrocajr commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +  - videojs 6.0
I'll get it right one of these days:)

2017-01-26 20:36 UTC, brandonocasey approved these changes

2017-01-27 10:38 UTC, mister-ben commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +In August of 2016, we [announced] our intention of removing flash as a part of the core video.js project.
Flash and Video.js should be capitalised throughout as proper nouns.

2017-02-03 21:52 UTC, gkatsev requested changes

2017-02-03 21:52 UTC, gkatsev commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +  - Video.js 6.0
tag is all lowercase: `video.js 6.0`

2017-02-03 21:52 UTC, gkatsev commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +In August of 2016, we [announced] our intention of removing flash as a part of the core video.js project.
needs to be `[announced][]` to use the link below.

2017-02-03 21:52 UTC, gkatsev commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +Chrome: [Chrome 56 disables flash by default]
needs the extra brackets here and in the rest of the links to be linked properly

2017-02-03 21:52 UTC, gkatsev commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +<script> var player = videojs('vid', {techOrder: ['flash']}); </script>
flash is added to the tech order automatically, might be worth mentioning.

2017-02-06 14:19 UTC, mrocajr commented on source/_drafts/Video.js-Flash-Removed-From-Core-Player.md
> +  - Video.js 6.0
All set.

2017-02-08 23:48 UTC, gkatsev approved these changes

2017-02-08 23:49 UTC, merged